# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

# version: '3.4'

# services:
#   tamagotchiapi:
#     image: tamagotchiapi
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 5000:5000

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tamagotchi_api_database;Username=postgres;Password=tamagotchipostgres
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tamagotchipostgres
      POSTGRES_DB: tamagotchi_api_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
