--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE "Jeremy Badger";
ALTER ROLE "Jeremy Badger" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "tamagotchi_api_database" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tamagotchi_api_database; Type: DATABASE; Schema: -; Owner: Jeremy Badger
--

CREATE DATABASE "tamagotchi_api_database" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LC_COLLATE = 'C' LC_CTYPE = 'en';


ALTER DATABASE "tamagotchi_api_database" OWNER TO "Jeremy Badger";

\connect "tamagotchi_api_database"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Feedings; Type: TABLE; Schema: public; Owner: Jeremy Badger
--

CREATE TABLE public."Feedings" (
    "Id" integer NOT NULL,
    "When" timestamp with time zone NOT NULL,
    "PetId" integer NOT NULL
);


ALTER TABLE public."Feedings" OWNER TO "Jeremy Badger";

--
-- Name: Feedings_Id_seq; Type: SEQUENCE; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE public."Feedings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Feedings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pets; Type: TABLE; Schema: public; Owner: Jeremy Badger
--

CREATE TABLE public."Pets" (
    "Id" integer NOT NULL,
    "Name" text,
    "Birthday" timestamp with time zone NOT NULL,
    "HungerLevel" integer NOT NULL,
    "HappinessLevel" integer NOT NULL,
    "LastInteractedWithDate" timestamp with time zone NOT NULL,
    "IsDead" boolean NOT NULL,
    "ImageUrl" text,
    "SpriteUrl" text
);


ALTER TABLE public."Pets" OWNER TO "Jeremy Badger";

--
-- Name: Pets_Id_seq; Type: SEQUENCE; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE public."Pets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Playtimes; Type: TABLE; Schema: public; Owner: Jeremy Badger
--

CREATE TABLE public."Playtimes" (
    "Id" integer NOT NULL,
    "When" timestamp with time zone NOT NULL,
    "PetId" integer NOT NULL
);


ALTER TABLE public."Playtimes" OWNER TO "Jeremy Badger";

--
-- Name: Playtimes_Id_seq; Type: SEQUENCE; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE public."Playtimes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Playtimes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Scoldings; Type: TABLE; Schema: public; Owner: Jeremy Badger
--

CREATE TABLE public."Scoldings" (
    "Id" integer NOT NULL,
    "When" timestamp with time zone NOT NULL,
    "PetId" integer NOT NULL
);


ALTER TABLE public."Scoldings" OWNER TO "Jeremy Badger";

--
-- Name: Scoldings_Id_seq; Type: SEQUENCE; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE public."Scoldings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Scoldings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: Jeremy Badger
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "Jeremy Badger";

--
-- Name: Feedings PK_Feedings; Type: CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Feedings"
    ADD CONSTRAINT "PK_Feedings" PRIMARY KEY ("Id");


--
-- Name: Pets PK_Pets; Type: CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Pets"
    ADD CONSTRAINT "PK_Pets" PRIMARY KEY ("Id");


--
-- Name: Playtimes PK_Playtimes; Type: CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Playtimes"
    ADD CONSTRAINT "PK_Playtimes" PRIMARY KEY ("Id");


--
-- Name: Scoldings PK_Scoldings; Type: CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Scoldings"
    ADD CONSTRAINT "PK_Scoldings" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Feedings_PetId; Type: INDEX; Schema: public; Owner: Jeremy Badger
--

CREATE INDEX "IX_Feedings_PetId" ON public."Feedings" USING btree ("PetId");


--
-- Name: IX_Playtimes_PetId; Type: INDEX; Schema: public; Owner: Jeremy Badger
--

CREATE INDEX "IX_Playtimes_PetId" ON public."Playtimes" USING btree ("PetId");


--
-- Name: IX_Scoldings_PetId; Type: INDEX; Schema: public; Owner: Jeremy Badger
--

CREATE INDEX "IX_Scoldings_PetId" ON public."Scoldings" USING btree ("PetId");


--
-- Name: Feedings FK_Feedings_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Feedings"
    ADD CONSTRAINT "FK_Feedings_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: Playtimes FK_Playtimes_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Playtimes"
    ADD CONSTRAINT "FK_Playtimes_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: Scoldings FK_Scoldings_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: Jeremy Badger
--

ALTER TABLE ONLY public."Scoldings"
    ADD CONSTRAINT "FK_Scoldings_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

