// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TamagotchiAPI.Models;

#nullable disable

namespace TamagotchiAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250716015958_SeedGlobalPets")]
    partial class SeedGlobalPets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TamagotchiAPI.Models.Feeding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Feedings");
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HappinessLevel")
                        .HasColumnType("integer");

                    b.Property<int>("HungerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastInteractedWithDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SpriteUrl")
                        .HasColumnType("text");

                    b.Property<string>("VisitorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5240),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5240),
                            Name = "Bulbasaur",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/1.png"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            Name = "Charmander",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/4.png"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            Name = "Squirtle",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/7.png"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            Name = "Caterpie",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/10.png"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5250),
                            Name = "Pikachu",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/25.png"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5260),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HappinessLevel = 0,
                            HungerLevel = 0,
                            ImageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
                            IsDead = false,
                            LastInteractedWithDate = new DateTime(2025, 7, 16, 1, 59, 58, 484, DateTimeKind.Utc).AddTicks(5260),
                            Name = "Eevee",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/133.png"
                        });
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Playtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Playtimes");
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Scolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Scoldings");
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Feeding", b =>
                {
                    b.HasOne("TamagotchiAPI.Models.Pet", null)
                        .WithMany("Feedings")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Playtime", b =>
                {
                    b.HasOne("TamagotchiAPI.Models.Pet", null)
                        .WithMany("Playtimes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Scolding", b =>
                {
                    b.HasOne("TamagotchiAPI.Models.Pet", null)
                        .WithMany("Scoldings")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TamagotchiAPI.Models.Pet", b =>
                {
                    b.Navigation("Feedings");

                    b.Navigation("Playtimes");

                    b.Navigation("Scoldings");
                });
#pragma warning restore 612, 618
        }
    }
}
